variables:
  DOC_SERVER: doc
  DOC_CENTER: /home/xl_ci/doc_center/nuclei_document
  DOC_NAME: nuclei_tools
  IMAGE: rego.corp.nucleisys.com/software/docbuilder
  IMAGE_TAG: latest

default:
  tags:
    - env::docker
    - net::outside
    - host::whml1
  image: $IMAGE:$IMAGE_TAG

stages:
  - build
  - deploy

## Job for build document
build_doc:
  stage: build
  interruptible: true
  retry: 1
  only:
    refs:
      - master
      - merge_requests
  artifacts:
    name: "${DOC_NAME}-${CI_COMMIT_SHA::8}"
    paths:
      - build/html
    expire_in: 2 day
  before_script:
      - pip3 install -U -r requirements.txt
      #- npm i wavedrom-cli
  script:
    - make clean
    - make pdf

## Job for deploy document to internal server
deploy_doc:
  stage: deploy
  interruptible: true
  #when: manual
  needs:
    - job: build_doc
  retry: 1
  only:
    refs:
      - master
  script:
    - ssh $DOC_SERVER "rm -rf $DOC_CENTER/$DOC_NAME/*"
    - ssh $DOC_SERVER "mkdir -p $DOC_CENTER/$DOC_NAME/"
    - cd build
    - scp -r html $DOC_SERVER:$DOC_CENTER/$DOC_NAME
    - echo "see generated html here http://doc/nuclei_document/$DOC_NAME/html/index.html"
  dependencies:
    - build_doc
  tags:
    - env::native
    - host::xls01
