# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
# sys.path.insert(0, os.path.abspath('.'))

# -- Project information -----------------------------------------------------
#don't put .pdf in pdfname
pdfname = "nuclei_tool_user_guide"

project = 'Nuclei Development Tool Guide'
copyright = '2019-Present, Nuclei'
author = 'Nuclei'

# The short X.Y version
version = '2023.10'

# The full version, including alpha/beta/rc tags
release = '2023.10'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx_rtd_theme',
    'breathe',
    'sphinx.ext.githubpages',
    'sphinx.ext.mathjax',
    'sphinx.ext.autosectionlabel',
    'sphinx_markdown_tables',
    'sphinxcontrib.wavedrom',
    'sphinxcontrib.inkscapeconverter',
    "sphinxcontrib.drawio",
    'sphinxcontrib.plantuml',
    'recommonmark'
]
wavedrom_html_jsinline = False

drawio_headless=True
drawio_no_sandbox=True

offline_skin_js_path = "asserts/default.js"
offline_wavedrom_js_path = "asserts/wavedrom.js"

highlight_language = "c"
autosectionlabel_prefix_document = True
numfig = True

suppress_warnings = ['autosectionlabel.*']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix = ['.rst', '.md']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# -- Options for HTML output -------------------------------------------------
# Show build timestamp
html_last_updated_fmt = ""

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

html_logo = 'asserts/logo/logo.png'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_search_language = "en"

html_theme_options = {
    'logo_only': True,
    'navigation_depth': 6
}

# -- Options for Breathe Project ---------------------------------------------
breathe_projects = {
}
breathe_default_project = ""
breathe_show_define_initializer = True

# -- Options for Latex output -------------------------------------------------
latex_logo = 'asserts/logo/logo.png'
latex_show_pagerefs = True
latex_toplevel_sectioning = 'chapter'
latex_show_urls = 'footnote'
latex_documents = [("index", "%s.tex"%(pdfname), project, author, "manual", False) ]

rst_prolog = """
.. |nuclei_contact| replace:: support@nucleisys.com
.. |nuclei_usercenter| replace:: http://user.nucleisys.com
.. |NMSIS| replace:: `NMSIS`_
.. _NMSIS: https://github.com/Nuclei-Software/NMSIS
.. |nuclei_sdk| replace:: `Nuclei SDK`_
.. _Nuclei SDK: https://github.com/Nuclei-Software/nuclei-sdk
.. |nuclei_download_center| replace:: `Nuclei Download Center`_
.. _Nuclei Download Center: https://nucleisys.com/download.php
.. |github| replace:: `Github`_
.. _Github: https://github.com
.. |gitee| replace:: `Gitee`_
.. _Gitee: https://gitee.com
.. |github_nuclei_sdk| replace:: `Nuclei SDK in Github`_
.. _Nuclei SDK in Github: https://github.com/Nuclei-Software/nuclei-sdk
.. |gitee_nuclei_sdk| replace:: `Nuclei SDK in Gitee`_
.. _Nuclei SDK in Gitee: https://gitee.com/Nuclei-Software/nuclei-sdk
.. |github_nuclei_sdk_release| replace:: `Nuclei SDK Release in Github`_
.. _Nuclei SDK Release in Github: https://github.com/Nuclei-Software/nuclei-sdk/releases
.. |teraterm| replace:: `TeraTerm in Windows`_
.. _TeraTerm in Windows: http://ttssh2.osdn.jp/
.. |minicom| replace:: `Minicom in Linux`_
.. _Minicom in Linux: https://help.ubuntu.com/community/Minicom
"""

rst_epilog = """
.. |nuclei_core| replace:: Nuclei N/NX/UX Class Processors
.. |nuclei_ncore| replace:: Nuclei N Class Processors
.. |nuclei_nxcore| replace:: Nuclei NX Class Processors
.. |nuclei_uxcore| replace:: Nuclei UX Class Processors
"""

# -- Extension configuration -------------------------------------------------

def setup(app):
    app.add_css_file("css/custom.css")
