name: Build Documentation

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build_deploy:
    name: Build documentation
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install Dependencies on Ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: |
          sudo apt-get update
          sudo apt-get install lftp python3 python3-pip make latexmk \
          texlive-full xindy texlive-latex-recommended texlive-xetex texlive-lang-cjk texlive-latex-extra texlive-fonts-recommended
          python3 -m pip install --upgrade pip
          pip install --upgrade setuptools==75.8.0 setuptools-scm==8.2.0
          # install xcffib seperately due to install fail
          pip install --use-pep517  xcffib==1.5.0
          pip install -r requirements.txt

    - name: Build Documentation
      run: |
        make all
        make pdf

    - name: Deploy Documentation
      if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}
      env:
          FTPUSER: ${{ secrets.FTPUSER }}
          FTPPWD: ${{ secrets.FTPPWD }}
          FTPSERVER: ${{ secrets.FTPSERVER }}
      run: |
        bash .github/ftp_deploy.sh $FTPUSER $FTPPWD $FTPSERVER build/html nuclei_tools
        echo "Click https://doc.nucleisys.com/nuclei_tools to view the latest deployment!"

    - name: Upload Documentation
      uses: actions/upload-artifact@v4
      with:
        # Artifact name
        name: nuclei_tools_doc
        # A file, directory or wildcard pattern that describes what to upload
        path: build/html
