name: Build Documentation

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  pull_request:

jobs:
  build_deploy:
    name: Build documentation
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:

    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install Dependencies on Ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: |
          sudo apt-get update
          sudo apt-get install lftp python3 make latexmk \
          texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
          sudo python3 -m pip install --upgrade pip
          sudo pip3 install -r requirements.txt

    - name: Build Documentation
      run: |
        make all
        make latexpdf
        cp build/latex/*.pdf build/html/

    - name: Deploy Documentation
      if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}
      env:
          FTPUSER: ${{ secrets.FTPUSER }}
          FTPPWD: ${{ secrets.FTPPWD }}
          FTPSERVER: ${{ secrets.FTPSERVER }}
      run: |
        bash .github/ftp_deploy.sh $FTPUSER $FTPPWD $FTPSERVER build/html nuclei_tools
        echo "Click https://doc.nucleisys.com/nuclei_tools to view the latest deployment!"

    - name: Upload Documentation
      uses: actions/upload-artifact@v3
      with:
        # Artifact name
        name: nuclei_tools_doc
        # A file, directory or wildcard pattern that describes what to upload
        path: build/html
